### ISSUE TITLE
Can't pass arguments to bash.exe

### ISSUE THREAD

**Issue by saschagehlich** [Tyriar/node-pty#13] opened 2016-12-13 07:20 UTC
The `argvToCommandLine` method in `pty_win.js` causes stuff like `bash.exe -c /usr/bin/zsh` to be escaped weirdly, causing `bash.exe` to print `-: invalid option`

**Comment by Tyriar** [comment] 2017-03-13 22:55
This should be fixed in the new release and being closed as a duplicate of https://github.com/Tyriar/node-pty/issues/41. You can specify args as a `string` on Windows which is what you want to use if you don't want the standard escaping to occur. https://github.com/Tyriar/node-pty/releases/tag/0.6.3

**Closed by Tyriar** 2017-03-13 22:55 UTC
Labels: bug, help wanted, windows
